# -*- coding: utf-8 -*-
"""Dados do site multilíngue. Para acrescentar um idioma, adicione a chave em UI e em GAMES[*]['hook']."""

LANGS = ["pt", "en", "es"]
DEFAULT = "en"                      # fallback e x-default
HTML_LANG = {"pt": "pt-BR", "en": "en", "es": "es"}

# ---------------------------------------------------------------- lojas por país
# tag = espaço para o código de afiliado de cada programa (um por país)
STORES = {
    "BR": {"name": "Amazon.com.br", "base": "https://www.amazon.com.br/s?k=", "tag": "TAG_BR"},
    "US": {"name": "Amazon.com",    "base": "https://www.amazon.com/s?k=",    "tag": "TAG_US"},
    "GB": {"name": "Amazon.co.uk",  "base": "https://www.amazon.co.uk/s?k=",  "tag": "TAG_UK"},
    "ES": {"name": "Amazon.es",     "base": "https://www.amazon.es/s?k=",     "tag": "TAG_ES"},
    "MX": {"name": "Amazon.com.mx", "base": "https://www.amazon.com.mx/s?k=", "tag": "TAG_MX"},
    "DE": {"name": "Amazon.de",     "base": "https://www.amazon.de/s?k=",     "tag": "TAG_DE"},
    "FR": {"name": "Amazon.fr",     "base": "https://www.amazon.fr/s?k=",     "tag": "TAG_FR"},
    "IT": {"name": "Amazon.it",     "base": "https://www.amazon.it/s?k=",     "tag": "TAG_IT"},
    "CA": {"name": "Amazon.ca",     "base": "https://www.amazon.ca/s?k=",     "tag": "TAG_CA"},
}
# país presumido quando não dá para saber, por idioma detectado
LANG_COUNTRY = {"pt": "BR", "es": "ES", "en": "US"}

# ---------------------------------------------------------------- textos de interface
UI = {
"pt": {
  "title":    "Need for Speed: a cronologia completa",
  "meta":     "Os 25 jogos da série Need for Speed, de 1994 a 2022, em ordem de lançamento, com onde comprar cada um.",
  "kicker":   "Cronologia da série",
  "h1":       "Need for Speed",
  "sub":      "Vinte e cinco jogos, cinco eras, de 1994 a 2022. A história completa da série, na ordem em que ela aconteceu.",
  "langlabel":"Idioma",
  "storelabel":"Comprar em",
  "buy":      "Ver preço",
  "studio":   "Estúdio",
  "eras_h":   "As cinco eras",
  "games_h":  "Os 25 jogos",
  "disclosure":"Esta página contém links de afiliado. Se você comprar por eles, podemos receber uma comissão, sem custo adicional para você.",
  "trademark":"Need for Speed é marca da Electronic Arts. Esta página não é oficial e não tem vínculo com a EA. As artes dos quadros são composições originais.",
    "carousel": "Galeria das eras",
  "prev":     "Anterior",
  "next":     "Próximo",
  "gotogame": "Ver este jogo",
  "switchnote":"Detectamos seu idioma automaticamente. Você pode trocar quando quiser.",
},
"en": {
  "title":    "Need for Speed: the complete timeline",
  "meta":     "All 25 Need for Speed games, 1994 to 2022, in release order, with where to buy each one.",
  "kicker":   "Series timeline",
  "h1":       "Need for Speed",
  "sub":      "Twenty-five games, five eras, 1994 to 2022. The full history of the series, in the order it happened.",
  "langlabel":"Language",
  "storelabel":"Buy from",
  "buy":      "Check price",
  "studio":   "Studio",
  "eras_h":   "The five eras",
  "games_h":  "All 25 games",
  "disclosure":"This page contains affiliate links. If you buy through them we may earn a commission, at no extra cost to you.",
  "trademark":"Need for Speed is a trademark of Electronic Arts. This page is unofficial and not affiliated with EA. The tile artwork is original.",
    "carousel": "Gallery of eras",
  "prev":     "Previous",
  "next":     "Next",
  "gotogame": "Jump to this game",
  "switchnote":"We detected your language automatically. You can change it any time.",
},
"es": {
  "title":    "Need for Speed: la cronología completa",
  "meta":     "Los 25 juegos de Need for Speed, de 1994 a 2022, en orden de lanzamiento, con dónde comprar cada uno.",
  "kicker":   "Cronología de la saga",
  "h1":       "Need for Speed",
  "sub":      "Veinticinco juegos, cinco eras, de 1994 a 2022. La historia completa de la saga, en el orden en que ocurrió.",
  "langlabel":"Idioma",
  "storelabel":"Comprar en",
  "buy":      "Ver precio",
  "studio":   "Estudio",
  "eras_h":   "Las cinco eras",
  "games_h":  "Los 25 juegos",
  "disclosure":"Esta página contiene enlaces de afiliado. Si compras a través de ellos podemos recibir una comisión, sin coste adicional para ti.",
  "trademark":"Need for Speed es una marca de Electronic Arts. Esta página no es oficial ni está afiliada a EA. Las ilustraciones son composiciones originales.",
    "carousel": "Galería de las eras",
  "prev":     "Anterior",
  "next":     "Siguiente",
  "gotogame": "Ir a este juego",
  "switchnote":"Detectamos tu idioma automáticamente. Puedes cambiarlo cuando quieras.",
},
}

LANG_NAME = {"pt": "Português", "en": "English", "es": "Español"}

# ---------------------------------------------------------------- eras
ERAS = {
"e1": {"span": "1994 – 2000", "color": "#7FA6B8",
       "pt": "A estrada aberta", "en": "The open road",   "es": "La carretera abierta"},
"e2": {"span": "2002 – 2006", "color": "#A855F7",
       "pt": "A rua e a noite", "en": "The street at night", "es": "La calle y la noche"},
"e3": {"span": "2007 – 2010", "color": "#E0533A",
       "pt": "A série se parte", "en": "The series splits", "es": "La saga se divide"},
"e4": {"span": "2010 – 2013", "color": "#FF8A1F",
       "pt": "O arcade da Criterion", "en": "Criterion's arcade", "es": "El arcade de Criterion"},
"e5": {"span": "2015 – 2022", "color": "#22D3B0",
       "pt": "O retorno da noite", "en": "Back to the night", "es": "El regreso de la noche"},
}

# ---------------------------------------------------------------- os 25 jogos
# style: (c1, c2, ti, motif, glow/p1, p2)
G = lambda **k: k
GAMES = [
 G(y=1994, name="The Need for Speed", pre="The", nm="Need for<br>Speed", era="e1",
   studio="EA Canada", q="The Need for Speed 3DO",
   st=("#1B3040","#0C161E","#E9F1F6","m-horizon","#9FC6DC",""),
   hook={"pt":"A estreia, no 3DO, com carros licenciados e vídeo de revista automotiva.",
         "en":"The debut, on 3DO, with licensed cars and motoring-magazine video.",
         "es":"El debut, en 3DO, con coches con licencia y vídeo de revista del motor."}),
 G(y=1997, name="Need for Speed II", pre="Need for Speed", nm="II", era="e1",
   studio="EA Canada", q="Need for Speed II PlayStation",
   st=("#7A5326","#2A1B0C","#FBEFDC","m-horizon","#E8B96A",""),
   hook={"pt":"Foco em hipercarros e circuitos exóticos, longe de qualquer realismo.",
         "en":"Hypercars and exotic circuits, a long way from realism.",
         "es":"Hiperdeportivos y circuitos exóticos, lejos de cualquier realismo."}),
 G(y=1998, name="Need for Speed III: Hot Pursuit", pre="Need for Speed III", nm="Hot<br>Pursuit", era="e1",
   studio="EA Canada", q="Need for Speed III Hot Pursuit",
   st=("#12274A","#070D1A","#E6EDF9","m-pursuit","#3B6BE0","#D6313A"),
   hook={"pt":"A polícia vira mecânica central pela primeira vez na série.",
         "en":"The police become a core mechanic for the first time.",
         "es":"La policía se convierte en mecánica central por primera vez."}),
 G(y=1999, name="Need for Speed: High Stakes", pre="Need for Speed", nm="High<br>Stakes", era="e1",
   studio="EA Canada", q="Need for Speed High Stakes",
   st=("#1D3A2E","#0A1611","#E7F3EC","m-stripe","#63A883",""),
   hook={"pt":"Dano no carro e corrida apostando o próprio veículo.",
         "en":"Car damage, and races where you wager your own car.",
         "es":"Daño en el coche y carreras apostando tu propio vehículo."}),
 G(y=2000, name="Need for Speed: Porsche Unleashed", pre="Need for Speed", nm="Porsche<br>Unleashed", era="e1",
   studio="EA Canada / Eden", q="Need for Speed Porsche Unleashed",
   st=("#5B6068","#16181C","#F2F3F5","m-track","#C8442F",""),
   hook={"pt":"Cinquenta anos de Porsche em um jogo só, o mais técnico da fase.",
         "en":"Fifty years of Porsche in one game, the most technical of the era.",
         "es":"Cincuenta años de Porsche en un solo juego, el más técnico de la etapa."}),
 G(y=2002, name="Need for Speed: Hot Pursuit 2", pre="Need for Speed", nm="Hot<br>Pursuit 2", era="e2",
   studio="EA Black Box", q="Need for Speed Hot Pursuit 2 PS2",
   st=("#0F2E63","#060B18","#E9F0FF","m-pursuit","#2F6BFF","#E5342F"),
   hook={"pt":"O primeiro da série na geração PS2 e Xbox.",
         "en":"The first entry of the PS2 and Xbox generation.",
         "es":"El primero de la saga en la generación PS2 y Xbox."}),
 G(y=2003, name="Need for Speed: Underground", pre="Need for Speed", nm="Under<br>ground", era="e2",
   studio="EA Black Box", q="Need for Speed Underground",
   st=("#2A0B4A","#050308","#F0E6FF","m-neon","#B24CFF",""),
   hook={"pt":"Vira a chave para tuning, noite e cultura de rua. O jogo que definiu a série.",
         "en":"Flips the series to tuning, night and street culture. The one that defined it.",
         "es":"Da el giro al tuning, la noche y la cultura callejera. El que definió la saga."}),
 G(y=2004, name="Need for Speed: Underground 2", pre="Need for Speed", nm="Under<br>ground 2", era="e2",
   studio="EA Canada / Black Box", q="Need for Speed Underground 2",
   st=("#4A0B39","#06040A","#FFE9FA","m-neon","#33E1FF",""),
   hook={"pt":"Mundo aberto e a customização visual mais profunda da franquia.",
         "en":"Open world and the deepest visual customization in the franchise.",
         "es":"Mundo abierto y la personalización visual más profunda de la franquicia."}),
 G(y=2005, name="Need for Speed: Most Wanted", pre="Need for Speed", nm="Most<br>Wanted", era="e2",
   studio="EA Canada / Black Box", q="Need for Speed Most Wanted 2005",
   st=("#525B66","#171A1F","#F7F4E8","m-halftone","#E0AC2B",""),
   hook={"pt":"Blacklist, perseguição e o filtro azulado que virou marca da série.",
         "en":"The Blacklist, the police chases, and the blue filter that became iconic.",
         "es":"La Blacklist, las persecuciones y el filtro azulado que se volvió icónico."}),
 G(y=2006, name="Need for Speed: Carbon", pre="Need for Speed", nm="Carbon", era="e2",
   studio="EA Canada / Black Box", q="Need for Speed Carbon",
   st=("#6B2A08","#0B0705","#FFEEDF","m-shard","#FF7A18","#FFC46B"),
   hook={"pt":"Corrida de cânion e disputa por território entre gangues.",
         "en":"Canyon duels and gang turf wars.",
         "es":"Duelos en el cañón y guerra de territorios entre bandas."}),
 G(y=2007, name="Need for Speed: ProStreet", pre="Need for Speed", nm="Pro<br>Street", era="e3",
   studio="EA Black Box", q="Need for Speed ProStreet",
   st=("#D8DBDF","#7C838C","#101215","m-stripe","#C0271E",""),
   hook={"pt":"Sai da rua e vai para o autódromo, à luz do dia. A virada mais impopular.",
         "en":"Off the street and onto the track, in daylight. The most unpopular turn.",
         "es":"Deja la calle por el circuito, a plena luz. El giro más impopular."}),
 G(y=2008, name="Need for Speed: Undercover", pre="Need for Speed", nm="Under<br>cover", era="e3",
   studio="EA Black Box", q="Need for Speed Undercover",
   st=("#243840","#080C0E","#E4EFF2","m-scan","#6E9AA8",""),
   hook={"pt":"Narrativa policial com atores em vídeo e um mundo aberto enorme.",
         "en":"An undercover-cop story with live-action video and a huge open world.",
         "es":"Trama de policía infiltrado con vídeo real y un mundo abierto enorme."}),
 G(y=2009, name="Need for Speed: Shift", pre="Need for Speed", nm="Shift", era="e3",
   studio="Slightly Mad Studios", q="Need for Speed Shift",
   st=("#E8E9EB","#5A5E64","#0E1013","m-track","#D62828",""),
   hook={"pt":"O braço de simulação da série, com foco na cabine e no piloto.",
         "en":"The series' simulation arm, built around the cockpit and the driver.",
         "es":"El brazo de simulación de la saga, centrado en la cabina y el piloto."}),
 G(y=2009, name="Need for Speed: Nitro", pre="Need for Speed", nm="Nitro", era="e3",
   studio="Firebrand / EA Montreal", q="Need for Speed Nitro Wii",
   st=("#FFC400","#E0431F","#1A0C05","m-halftone","#00C2D6",""),
   hook={"pt":"Versão estilizada e cartunesca, feita para Wii e DS.",
         "en":"A stylized, cartoon-leaning take built for Wii and DS.",
         "es":"Una versión estilizada y caricaturesca, hecha para Wii y DS."}),
 G(y=2010, name="Need for Speed: World", pre="Need for Speed", nm="World", era="e3",
   studio="EA Singapore / Black Box", q="Need for Speed World",
   st=("#08303A","#030C10","#DFF7F5","m-scan","#2BE3C8",""),
   hook={"pt":"MMO gratuito para PC. Foi desligado em 2015 e hoje só existe em servidor de fã.",
         "en":"A free-to-play PC MMO. Shut down in 2015, alive today only on fan servers.",
         "es":"Un MMO gratuito para PC. Cerró en 2015 y hoy solo vive en servidores de fans."}),
 G(y=2010, name="Need for Speed: Hot Pursuit", pre="Need for Speed", nm="Hot<br>Pursuit", era="e4",
   studio="Criterion Games", q="Need for Speed Hot Pursuit Remastered",
   st=("#111A33","#06080F","#EAF0FF","m-pursuit","#2E5CFF","#FF2A2A"),
   hook={"pt":"O Autolog e a rivalidade assíncrona entre amigos. Tem versão remasterizada.",
         "en":"Autolog and asynchronous rivalry between friends. A remaster is available.",
         "es":"Autolog y la rivalidad asíncrona entre amigos. Tiene versión remasterizada."}),
 G(y=2011, name="Shift 2: Unleashed", pre="Shift 2", nm="Un<br>leashed", era="e4",
   studio="Slightly Mad Studios", q="Shift 2 Unleashed",
   st=("#2A2E23","#0A0B07","#F0FFD9","m-track","#B6FF23",""),
   hook={"pt":"A última investida da série na simulação pura.",
         "en":"The series' last push into pure simulation.",
         "es":"La última apuesta de la saga por la simulación pura."}),
 G(y=2011, name="Need for Speed: The Run", pre="Need for Speed", nm="The Run", era="e4",
   studio="EA Black Box", q="Need for Speed The Run",
   st=("#3D4E5C","#0D1216","#EEF4F8","m-horizon","#FF7B29",""),
   hook={"pt":"Corrida costa a costa pelos Estados Unidos, com trechos a pé.",
         "en":"A coast-to-coast race across the US, with on-foot sequences.",
         "es":"Una carrera de costa a costa por Estados Unidos, con tramos a pie."}),
 G(y=2012, name="Need for Speed: Most Wanted", pre="Need for Speed", nm="Most<br>Wanted", era="e4",
   studio="Criterion Games", q="Need for Speed Most Wanted 2012",
   st=("#B24A0A","#0D0703","#FFF0E2","m-stripe","#FFA51F",""),
   hook={"pt":"Releitura em mundo aberto, sem relação de enredo com o de 2005.",
         "en":"An open-world reimagining, unrelated in story to the 2005 game.",
         "es":"Una relectura en mundo abierto, sin relación argumental con el de 2005."}),
 G(y=2013, name="Need for Speed Rivals", pre="Need for Speed", nm="Rivals", era="e4",
   studio="Ghost Games / Criterion", q="Need for Speed Rivals",
   st=("#0B3A44","#070A0C","#E9F6F8","m-pursuit","#12B5C4","#F26A1B"),
   hook={"pt":"Título de lançamento do PS4 e do Xbox One, com polícia e piloto jogáveis.",
         "en":"A PS4 and Xbox One launch title, with both cop and racer playable.",
         "es":"Título de lanzamiento de PS4 y Xbox One, con policía y piloto jugables."}),
 G(y=2015, name="Need for Speed", pre="Reboot", nm="Need for<br>Speed", era="e5",
   studio="Ghost Games", q="Need for Speed 2015 PS4",
   st=("#2B1050","#04030A","#EDE6FF","m-neon","#7C4DFF",""),
   hook={"pt":"Reboot sempre online, com noite permanente e forte apelo ao Underground.",
         "en":"An always-online reboot, permanent night, heavy Underground nostalgia.",
         "es":"Un reinicio siempre en línea, noche permanente y mucha nostalgia de Underground."}),
 G(y=2015, name="Need for Speed: No Limits", pre="Need for Speed", nm="No<br>Limits", era="e5",
   studio="Firemonkeys", q="Need for Speed No Limits",
   st=("#0A1E52","#04060F","#E3F2FF","m-halftone","#22D3EE",""),
   hook={"pt":"A entrada da franquia no celular, gratuito para iOS e Android.",
         "en":"The franchise's move to mobile, free on iOS and Android.",
         "es":"La entrada de la franquicia en el móvil, gratis en iOS y Android."}),
 G(y=2017, name="Need for Speed Payback", pre="Need for Speed", nm="Payback", era="e5",
   studio="Ghost Games", q="Need for Speed Payback",
   st=("#8A5A12","#170D06","#FFF3DE","m-horizon","#F2B33D",""),
   hook={"pt":"Trio de personagens, cenário de deserto e uma história de vingança.",
         "en":"Three playable characters, a desert setting, and a revenge story.",
         "es":"Trío de personajes, escenario desértico y una historia de venganza."}),
 G(y=2019, name="Need for Speed Heat", pre="Need for Speed", nm="Heat", era="e5",
   studio="Ghost Games", q="Need for Speed Heat",
   st=("#5B0B54","#050510","#FFE9FB","m-neon","#22E6C8",""),
   hook={"pt":"Ciclo de dia e noite, com risco que cresce quanto mais você corre.",
         "en":"A day and night cycle, with risk that climbs the longer you race.",
         "es":"Ciclo de día y noche, con un riesgo que crece cuanto más corres."}),
 G(y=2022, name="Need for Speed Unbound", pre="Need for Speed", nm="Unbound", era="e5",
   studio="Criterion Games", q="Need for Speed Unbound",
   st=("#EDEFF2","#4A4F58","#0B0C0E","m-shard","#00E0FF","#C6FF3D"),
   hook={"pt":"Traço de anime sobre carro fotorrealista. O último da série até agora.",
         "en":"Anime linework over photoreal cars. The most recent entry so far.",
         "es":"Trazo de anime sobre coches fotorrealistas. El más reciente hasta ahora."}),
]
